name: 'Shopify Theme Deploy Previews (Forked version)'
description: 'Create deploy previews of commits in Pull Requests'
author: 'wyugen'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  SHOPIFY_STORE:
    description: 'The shopify development store (as store.myshopify.com)'
    required: true
  SHOPIFY_APP_PW:
    description: 'The private app password used with themekit'
    required: true
  SHOPIFY_API_KEY:
    description: 'API Key for private app'
    required: true
  SHOPIFY_API_VERSION:
    description: 'API Version of Shopify Admin API'
    required: true
  github-token:
    description: 'Authentication Token'
    required: true
outputs:
  theme-id:
    description: 'Deployed theme id'
  deploy-url:
    description: 'The time'
runs: 
  using: 'node12'
  main: 'dist/index.js'
